version: '3'

services: 
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    networks:
      - postgres_compose_network_1
  
  pgadmin_compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres_db
    volumes:
      - ${PGADMIN_VOLUME}:/var/lib/pgadmin
    networks:
      - postgres_compose_network_1

networks: 
  postgres_compose_network_1:
    driver: bridge