version: '3'

services: 
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data